# Generated by Django 3.0.2 on 2020-01-20 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foopaPWA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foopaPWA.User'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foopaPWA.User'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_place',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=16),
        ),
    ]
