# Generated by Django 3.0.2 on 2020-01-20 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foopaPWA', '0002_auto_20200120_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fname',
            new_name='fist_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='lname',
            new_name='last_name',
        ),
    ]
