# Generated by Django 3.0.2 on 2020-01-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foopaPWA', '0004_auto_20200120_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_code',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='match_length',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='match_players_No',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
