# Generated by Django 3.0.2 on 2020-01-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foopaPWA', '0005_auto_20200121_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_owner',
        ),
    ]
