# Generated by Django 3.0.2 on 2020-01-24 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foopaPWA', '0006_remove_match_match_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_id',
        ),
    ]
