# Generated by Django 3.0.2 on 2020-01-24 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foopaPWA', '0007_remove_profile_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
