# Generated by Django 3.0.2 on 2020-01-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foopaPWA', '0013_matchrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile-defulat.png', null=True, upload_to='profile_pic'),
        ),
    ]
