# Generated by Django 3.0.2 on 2020-01-29 22:14

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('foopaPWA', '0014_auto_20200129_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_datej',
            field=django_jalali.db.models.jDateField(null=True),
        ),
    ]
