# Generated by Django 3.0.2 on 2020-01-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foopaPWA', '0015_match_match_datej'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_game',
            field=models.CharField(default='footbal', max_length=25, null=True),
        ),
    ]
