# Generated by Django 3.0.2 on 2020-01-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foopaPWA', '0017_auto_20200130_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('temp_pass', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('register_date_time', models.DateTimeField()),
                ('register_time_expire', models.DateTimeField()),
            ],
        ),
    ]
